# AnglerOS firmware builder
#
# This script was generated by AnglerOS for your printer. It builds Marlin
# firmware (firmware.uf2) from your configuration - fully automated. No GitHub,
# no manual PlatformIO setup.
#
# HOW TO RUN (Windows):
#   Right-click this file -> "Run with PowerShell"
#   ...or in a terminal:  powershell -ExecutionPolicy Bypass -File .\angleros-build.ps1
#
# Needs Git and Python installed (the script installs PlatformIO itself).

$ErrorActionPreference = 'Stop'

# --- Injected by AnglerOS ---------------------------------------------------
$MarlinRef  = '__MARLIN_REF__'
$PioEnv     = '__PIO_ENV__'
$FwArtifact = '__FW_ARTIFACT__'
$FlashHint  = '__FLASH_HINT__'
$ConfigIni = @'
__CONFIG_INI__
'@
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "AnglerOS firmware builder" -ForegroundColor Cyan
Write-Host "Marlin ref: $MarlinRef   env: $PioEnv"
Write-Host ""

# Workspace under LocalAppData so Marlin is cloned once and reused.
$work   = Join-Path $env:LOCALAPPDATA 'AnglerOS'
$marlin = Join-Path $work 'marlin-build'
New-Item -ItemType Directory -Force -Path $work | Out-Null

# --- Prerequisites ---------------------------------------------------------
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  throw "Git is not installed. Get it from https://git-scm.com/download/win, then re-run."
}
$py = (Get-Command python -ErrorAction SilentlyContinue).Source
if (-not $py) { $py = (Get-Command py -ErrorAction SilentlyContinue).Source }
if (-not $py) {
  throw "Python is not installed. Get it from https://www.python.org/downloads/ (tick 'Add Python to PATH'), then re-run."
}

# PlatformIO: use an existing CLI, the VS Code extension's copy, or pip-install it.
$pio = (Get-Command pio -ErrorAction SilentlyContinue).Source
if (-not $pio) {
  $penv = Join-Path $env:USERPROFILE '.platformio\penv\Scripts\platformio.exe'
  if (Test-Path $penv) { $pio = $penv }
}
$usePyModule = $false
if (-not $pio) {
  Write-Host "Installing PlatformIO (one-time, may take a minute)..." -ForegroundColor Yellow
  & $py -m pip install --user --upgrade platformio
  if ($LASTEXITCODE -ne 0) { throw "PlatformIO install failed." }
  $usePyModule = $true   # invoke via 'python -m platformio'
}

function Invoke-Pio {
  param([string[]]$PioArgs)
  if ($usePyModule) { & $py -m platformio @PioArgs }
  else { & $pio @PioArgs }
}

# --- Clone Marlin at the required ref (re-clone if it changed) --------------
$refMarker = Join-Path $marlin '.angleros-ref'
if (Test-Path $marlin) {
  $have = if (Test-Path $refMarker) { (Get-Content $refMarker -Raw).Trim() } else { '' }
  if ($have -ne $MarlinRef) {
    Write-Host "Existing Marlin is '$have' but need '$MarlinRef' - re-cloning..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force $marlin
  } else {
    Write-Host "Reusing Marlin clone ($MarlinRef)." -ForegroundColor Yellow
  }
}
if (-not (Test-Path $marlin)) {
  Write-Host "Cloning MarlinFirmware/Marlin @ $MarlinRef ..." -ForegroundColor Cyan
  git clone --depth 1 --branch $MarlinRef https://github.com/MarlinFirmware/Marlin.git $marlin
  if ($LASTEXITCODE -ne 0) { throw "git clone failed." }
  Set-Content -Path $refMarker -Value $MarlinRef
}

# --- Apply the embedded config (UTF-8, no BOM) -----------------------------
$cfgPath = Join-Path $marlin 'Marlin\config.ini'
[System.IO.File]::WriteAllText($cfgPath, $ConfigIni)
Write-Host "Applied your configuration." -ForegroundColor Green

# --- Build -----------------------------------------------------------------
Write-Host "Building (first run downloads the toolchain - a few minutes)..." -ForegroundColor Cyan
Push-Location $marlin
try { Invoke-Pio @('run', '-e', $PioEnv) } finally { Pop-Location }

$buildDir = Join-Path $marlin ".pio\build\$PioEnv"
$fw = Join-Path $buildDir $FwArtifact
if (-not (Test-Path $fw)) {
  # Fall back to the newest .uf2/.bin the build produced.
  $fw = Get-ChildItem -Path $buildDir -Include *.uf2, *.bin -File -Recurse -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $fw -or -not (Test-Path $fw)) { throw "Build finished but no firmware file was produced. See the log above." }

$dest = Join-Path ([Environment]::GetFolderPath('Desktop')) (Split-Path $fw -Leaf)
Copy-Item $fw $dest -Force

Write-Host ""
Write-Host "SUCCESS - firmware saved to your Desktop:" -ForegroundColor Green
Write-Host "  $dest" -ForegroundColor Green
Write-Host ""
Write-Host "To flash:" -ForegroundColor Green
Write-Host "  $FlashHint" -ForegroundColor Green
try { Start-Process (Split-Path $dest) } catch {}
