#!/usr/bin/env bash
# AnglerOS firmware builder (macOS / Linux)
#
# Generated by AnglerOS for your printer. Builds Marlin firmware from your
# configuration - fully automated. No GitHub, no manual PlatformIO setup.
#
# HOW TO RUN:
#   bash angleros-build.sh
#
# Needs git and python3 installed (the script installs PlatformIO itself).

set -euo pipefail

# --- Injected by AnglerOS ---------------------------------------------------
MARLIN_REF='__MARLIN_REF__'
PIO_ENV='__PIO_ENV__'
FW_ARTIFACT='__FW_ARTIFACT__'
FLASH_HINT='__FLASH_HINT__'
CONFIG_INI="$(cat <<'ANGLEROS_EOF'
__CONFIG_INI__
ANGLEROS_EOF
)"
# ---------------------------------------------------------------------------

echo
echo "AnglerOS firmware builder"
echo "Marlin ref: ${MARLIN_REF}   env: ${PIO_ENV}"
echo

work="${XDG_DATA_HOME:-$HOME/.local/share}/AnglerOS"
marlin="${work}/marlin-build"
mkdir -p "${work}"

# --- Prerequisites ---------------------------------------------------------
command -v git >/dev/null 2>&1 || { echo "ERROR: git is not installed. Install it, then re-run."; exit 1; }
if command -v python3 >/dev/null 2>&1; then PY=python3
elif command -v python >/dev/null 2>&1; then PY=python
else echo "ERROR: python3 is not installed. Install it, then re-run."; exit 1; fi

# PlatformIO: existing CLI, the VS Code extension's copy, or pip-install it.
if command -v pio >/dev/null 2>&1; then
  PIO=(pio)
elif [ -x "$HOME/.platformio/penv/bin/platformio" ]; then
  PIO=("$HOME/.platformio/penv/bin/platformio")
else
  echo "Installing PlatformIO (one-time, may take a minute)..."
  "$PY" -m pip install --user --upgrade platformio
  PIO=("$PY" -m platformio)
fi

# --- Clone Marlin at the required ref (re-clone if it changed) --------------
ref_marker="${marlin}/.angleros-ref"
if [ -d "${marlin}" ]; then
  have="$( [ -f "${ref_marker}" ] && cat "${ref_marker}" || echo '' )"
  if [ "${have}" != "${MARLIN_REF}" ]; then
    echo "Existing Marlin is '${have}' but need '${MARLIN_REF}' - re-cloning..."
    rm -rf "${marlin}"
  else
    echo "Reusing Marlin clone (${MARLIN_REF})."
  fi
fi
if [ ! -d "${marlin}" ]; then
  echo "Cloning MarlinFirmware/Marlin @ ${MARLIN_REF} ..."
  git clone --depth 1 --branch "${MARLIN_REF}" https://github.com/MarlinFirmware/Marlin.git "${marlin}"
  printf '%s' "${MARLIN_REF}" > "${ref_marker}"
fi

# --- Apply the embedded config ---------------------------------------------
printf '%s\n' "${CONFIG_INI}" > "${marlin}/Marlin/config.ini"
echo "Applied your configuration."

# --- Build -----------------------------------------------------------------
echo "Building (first run downloads the toolchain - a few minutes)..."
( cd "${marlin}" && "${PIO[@]}" run -e "${PIO_ENV}" )

build_dir="${marlin}/.pio/build/${PIO_ENV}"
fw="${build_dir}/${FW_ARTIFACT}"
if [ ! -f "${fw}" ]; then
  fw="$(find "${build_dir}" -maxdepth 1 \( -name '*.uf2' -o -name '*.bin' \) -print 2>/dev/null | head -n1)"
fi
[ -n "${fw}" ] && [ -f "${fw}" ] || { echo "ERROR: build finished but no firmware file was produced."; exit 1; }

dest="$HOME/Desktop"
[ -d "${dest}" ] || dest="$HOME"
cp -f "${fw}" "${dest}/"

echo
echo "SUCCESS - firmware saved to: ${dest}/$(basename "${fw}")"
echo
echo "To flash:"
echo "  ${FLASH_HINT}"
